<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Copyright>Copyright (c) 2023 websyncio</Copyright>
    <Description>XCSS selectors support</Description>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Version>1.0.4</Version>
    <FileVersion>1.0.4</FileVersion>
    <AssemblyVersion>1.0.4</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.9.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
